spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://94.191.12.180:3306/cc_blogweb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true



com:
  sipingsoft:
    static-root: http://94.191.12.180/static
    web-root:  http://94.191.12.180
    image-path:  http://94.191.12.180/image

#支付图片存储路径
paytype-path: /usr/local/soft/tomcat8.5.34/apache-tomcat-8.5.34/webapps/payType/

#文章缩略图存储路径
preview-path: /usr/local/soft/tomcat8.5.34/apache-tomcat-8.5.34/webapps/preview/