server:
  tomcat:
    max-threads: 800
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /
#    session:
#      timeout: 3000s  #springboot2.0 设置session过期时间的方法
#运行环境
spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    # jackson时间格式化
  jackson:
      time-zone: GMT+8 #时区
      date-format: yyyy-MM-dd HH:mm:ss
      serialization:
        write-dates-as-timestamps: false
  mvc:
    static-path-pattern: /static #指定springboot默认映射的文件夹
    #throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: true
#
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.sipingsoft.*.entity
