spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://94.191.12.180:3306/cc_blogweb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
      filter:
          stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: true
          wall:
              config:
                  multi-statement-allow: true



com:
  sipingsoft:
    static-root: http://app.blog.com/static
    web-root: http://app.blog.com
    image-path: http://app.blog.com/image

#支付图片存储路径
paytype-path: D:/IDEA/workspace/java-web/payType/

#文章缩略图存储路径
preview-path: D:/IDEA/workspace/java-web/preview/